### ISSUE TITLE
HiDPI bug in GUI? Misaligned buttons, very confused

### ISSUE THREAD

**Issue by Darthagnon** [nuttyartist/notes#521] opened 2023-03-11 09:40 UTC
![Notes_g90eHH4yJN](https://user-images.githubusercontent.com/20792748/224476709-a7c836b7-2da2-414e-9f24-9675558f993c.png)

... I have a HiDPI 1080p screen (I use [XP Explorer](https://windows10-dpi-fix.xpexplorer.com/) as a global compatibility patch on my PC), and that's what it looks like... I'm very confused by what I'm looking at.

- 2 separate hamburger settings menus: Aa and `. . .` - why not combine both into one settings menu ⚙ ?
- Random floating "Notes 📁" line
- Same thing happens with "Tags 💡"
- Editor settings window:
  - Aa settings x3, overlapping with font names, and multiple microscopic Next buttons (I'm guessing this is font settings, but it's broken for me)
  - Unlabelled +/- buttons (Trial and error: font size)
  - Unlabelled Full Width ➡⬅ buttons (uncertain purpose)
  - Rest all settings button is very prominent and large... there's not that many settings that would ever need resetting, and Reset All shouldn't be that easy to click in my opinion.

**Comment by zjeffer** [comment] 2023-03-11 11:45
Thanks for reporting.

* The HiDPI bug is a known issue, but not much progress is being made sadly. Here's an existing issue tracking it: https://github.com/nuttyartist/notes/issues/39.  
* We're thinking about implementing a complete settings menu, and replacing the Aa button with something better: https://github.com/nuttyartist/notes/issues/309
* I completely agree native window decorations look much better on Windows and should be the default, but this is something @nuttyartist has to decide.
* We indeed need to look into improving the editor settings window, but we don't really have any designers or concrete ideas/mockups for this as far as I know.
  * The arrow buttons change the margins of the text editor. Full width makes the text fill the full width of the editor window, while the arrow buttons make the margins larger or smaller.

Closing as a duplicate of #39. I'll open a new issue with your comments about the editor settings.

**Closed by zjeffer** 2023-03-11 11:45 UTC

**Comment by nuttyartist** [comment] 2023-03-11 14:31
@Darthagnon, thanks for your feedback! It's highly appreciated.

> I completely agree native window decorations look much better on Windows and should be the default, but this is something @nuttyartist has to decide.
> Native window looks much better on Windows, too, not sure why it's not the default?
I got this feedback enough, and from my last testing I also thought about it myself. We should make native window the default, until we can draw custom native window ourselves.

> 2 separate hamburger settings menus: Aa and . . . - why not combine both into one settings menu ⚙ ?
Let's continue the discussion in #309 

> Random floating "Notes 📁" line
> Same thing happens with "Tags 💡"
> Aa settings x3, overlapping with font names, and multiple microscopic Next buttons (I'm guessing this is font settings, but it's broken for me)

That's the HIDPI bug @zjeffer mentioned

> Editor settings window:
> Unlabelled +/- buttons (Trial and error: font size)
> Unlabelled Full Width ➡⬅ buttons (uncertain purpose)
> Rest all settings button is very prominent and large... there's not that many settings that would ever need resetting,  and Reset All shouldn't be that easy to click in my opinion.

Fair criticism! You're right. I'll open an issue to add proper labels and make the reset all settings button smaller.
Oh, maybe @zjeffer beat me to it.
