### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by chromer030** [nuttyartist/notes#605] opened 2023-07-27 10:11 UTC
Trying to run qt6 variant on Arch Linux, But :

Version : 2.2.0
Package : [notes-2.2.0_x86_64-qt6-fedora-36.rpm](https://github.com/nuttyartist/notes/releases/download/V2.2.0/notes-2.2.0_x86_64-qt6-fedora-36.rpm)

```
warning: copy relocation against non-copyable protected symbol `_ZN19QItemSelectionModel16staticMetaObjectE' in `/usr/lib/libQt6Core.so.6'
./notes: _ZN19QItemSelectionModel16staticMetaObjectE: /usr/lib/libQt6Core.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS
```

Version : 2.2.0
Package : [notes-2.2.0_x86_64-qt6-opensuse-leap-15.5.rpm](https://github.com/nuttyartist/notes/releases/download/V2.2.0/notes-2.2.0_x86_64-qt6-opensuse-leap-15.5.rpm)

```
./notes: /usr/lib/libQt6Widgets.so.6: version `Qt_6.4.2_PRIVATE_API' not found (required by ./notes)
```

Running OK : [notes_2.2.0_amd64-qt6-ubuntu-jammy.deb](https://github.com/nuttyartist/notes/releases/download/V2.2.0/notes_2.2.0_amd64-qt6-ubuntu-jammy.deb)

**Comment by zjeffer** [comment] 2023-07-27 10:55
On Arch linux, you should install through the AUR: https://aur.archlinux.org/packages/notes (or https://aur.archlinux.org/packages/notes-git for the latest master version). 

I'm currently updating the AUR packages to the latest version, I'll let you know when it's done.

**Comment by zjeffer** [comment] 2023-07-27 12:07
@chromer030 Can you test the `notes` package in the AUR? Should be updated now.

**Comment by chromer030** [comment] 2023-07-27 18:36
@zjeffer , Yeah Thanks for update, i know that it works, and it works cuz it's compiled against QT configuration and patchset of Arch.

The point of this issue was about different qt architecture of provided binaries, i though maybe it's a bug.

@nuttyartist 
So if you think everything is correct, feel free to close the issue.

Thanks.

**Comment by nuttyartist** [comment] 2023-07-28 11:43
So can we close this, @zjeffer?

**Comment by zjeffer** [comment] 2023-07-28 11:44
If someone tested the RPM packages on Fedora and OpenSUSE, then yes. I don't have a VM set up to test that.

**Comment by guihkx** [comment] 2023-07-28 17:18
>The point of this issue was about different qt architecture of provided binaries, i thought maybe it's a bug.

That's not a bug. Different Linux distributions will provide different versions of Qt, so if you want to avoid compatibility issues, you should build the app using Qt libraries provided by your distro.

**Closed by guihkx** 2023-07-28 17:18 UTC
Labels: Bug
