### ISSUE TITLE
Font selection and settings not exactly as expected

### ISSUE THREAD

**Issue by luc0x61** [nuttyartist/notes#517] opened 2023-03-10 07:57 UTC
I'm running Notes 2.1.0, just installed on Windows 11 pro 22H2, Italian localization. The following is what I get just typing a first note: clearly something is wrong with font selection and attributes

![immagine](https://user-images.githubusercontent.com/56227954/224256802-ad11d9c9-b978-4f91-95f8-4673980849e3.png)

Additionally: can the font be switched/selected in some settings?

**Comment by nuttyartist** [comment] 2023-03-10 08:04
Hey, @luc0x61!

What's the problem here? It's not quite clear to me.

> Additionally: can the font be switched/selected in some settings?

Yes, we know it's not very clear so we are planning to change the button to a gear icon. But here it is:


![test](https://user-images.githubusercontent.com/16375940/224258346-15de4a1c-52b4-4eed-bf81-7e4ce5c1e9bc.gif)

**Comment by bjorn** [comment] 2023-03-10 08:19
> What's the problem here? It's not quite clear to me.

I believe @luc0x61 is referring to the italic and bold text being a lot smaller than the rest of the text. This is a duplicate of #335.

**Comment by nuttyartist** [comment] 2023-03-10 08:20
Oh, probably. Very annoying indeed. @luc0x61 If that's the case, we will close this issue, but know that we'll be working on that for our next release.

**Comment by luc0x61** [comment] 2023-03-10 11:03
Oh ok, sorry for the silly question about font selection 😄

**Comment by nuttyartist** [comment] 2023-03-10 12:10
Don't blame yourself if the food tastes bad, blame the chef! It's our responsibility to make the different features easily discoverable. So we'll work on that. Thanks, I'll close this issue now.

**Closed by nuttyartist** 2023-03-10 12:10 UTC
