### ISSUE TITLE
Duplicated notes after restart

### ISSUE THREAD

**Issue by enesates** [nuttyartist/notes#199] opened 2018-02-26 12:18 UTC
When I open the application I see more than one similar notes which have different versions according to changes. If the note is a bit long you can see more than one hundred notes which have different versions of it.

OS: Ubuntu GNU/Linux 16.04 LTS
Branch: dev  

![duplicated notes](https://user-images.githubusercontent.com/1292675/36670122-45724eec-1b08-11e8-88f2-34608c3ce6dc.png)

**Comment by nuttyartist** [comment] 2018-02-26 16:03
@theshadowx I thought this bug was fixed in #175.

@enesates do you have the latest version of Notes installed from our website?

**Comment by theshadowx** [comment] 2018-02-26 16:19
indeed, I'll check this evening.

**Comment by theshadowx** [comment] 2018-02-26 21:36
I can't duplicate the issue

**Comment by enesates** [comment] 2018-02-26 22:15
I am always fetching the latest version from dev branch. But let me check tomorrow is there any error or sth while building in QT Creator.
I added executable file in 'build-Notes-Desktop_Qt_5_8_0_GCC_64bit-Debug' directory to startup applications.
I am also sorry about I couldn't see #175 even searched for it.

**Comment by theshadowx** [comment] 2018-02-26 23:12
The Ubuntu 16.04 contains in it's repository Qt5.5.1, and you are compiling with Qt5.8.0.
so when you double click on the executable from your desktop it will use Qt5.5.1, apart if you made your desktop to use Qt5.8.0. maybe some features are not loaded which makes the app not working correctly. (I'm just stipulating here)

Could you try to compile the app with Qt5.5.1 and see if the issue still appears.

> I am also sorry about I couldn't see #175 even searched for it.

no problem.

**Comment by enesates** [comment] 2018-02-27 07:55
It looks fine today. I have added some notes there and will observe until tomorrow. I will try your steps and let you know if it happens again, but we can say it won't fix right now because of #175 .

I am not sure but I switched branch to the aesthetic-changes a few months ago. Then switched back to the dev recently. There might have been some building issues. Btw, I am not totally sure.

**Comment by theshadowx** [comment] 2018-02-27 09:13
@enesates I think it's a critical issue, so we have to fix it if it appears again. But also we need to be able reproduce  this issue, to be able to pinpoint from where it comes.

There have been many modifications since the aesthetic-changes branch was created.

If you met this issue again, could you please describe what was done before closing the app.
Thanks.

**Comment by enesates** [comment] 2018-02-27 10:00
- dev branch is updated.
- I built the app using Qt Creator 5.5.1 as you said.
- Added some notes ('test' sth)
- Added executable file in **build-Notes-Desktop_Qt_5_5_1_GCC_64bit-Debug** directory to the startup applications.
- Restarted Ubuntu 16.04
- Result is same as you can see.

![screenshot_test](https://user-images.githubusercontent.com/1292675/36722097-b2e82644-1bbd-11e8-86ad-b49220c3c6a2.png)

**Comment by enesates** [comment] 2018-02-27 10:09
I didn't want to send all data but if you need I have this from sqlitebrowser

![screenshot_002](https://user-images.githubusercontent.com/1292675/36722731-66e9cb1a-1bbf-11e8-97fc-e7de62d63a3f.png)

**Comment by enesates** [comment] 2018-02-27 10:28
Finally it looks good but I did this

- Cloned the repository in a new directory
- Built using Qt 5.8.0
- Cleaned Awesomeness directory (I had them: _notes.db, Notes.ini, oldNotes.ini, oldTrash.ini, Settings.ini, Trash.ini_)
- Added new notes
- After restart everything looks fine

I will let you know if it is appeared again. I will keep eye on it.
I think it was related with the files in Awesomeness directory but not have so many idea, btw.

If you need any details, testing or sth please let me know.
Thank you..

**Comment by nuttyartist** [comment] 2018-02-27 10:30
Interesting. So maybe it was the Qt version? Did you try cleaning the Awesomeness directory before trying the new Qt version?

Thanks for helping testing out this bug. Let us know if you ever encounter it again.

**Comment by theshadowx** [comment] 2018-02-27 10:41
@enesates it's weird that you have oldTrash.ini and Trash.ini at the same time.

I guess you had an old version (0.9) and then you updated to the last one, so data was exported to sqlitedb.

so then it should rename the files Notes.ini and Trash.ini to oldNotes.ini and oldTrash.ini, which means that you shouldn't have oldBlaBla.ini and BlaBla.ini in the same folder

**Comment by nuttyartist** [comment] 2018-02-27 10:48
Indeed, it's weird. Our app automatically renames Notes.ini and Trash.ini (used by the old version) to oldNotes.ini and oldTrash.ini when the new version is running.

@enesates I guess that even after running the new version, you ran the old version again? Which probably added Notes.ini and Trash.ini on top of everything.

**Comment by enesates** [comment] 2018-02-27 11:05
I did it a few weeks ago. Switching branches, building them and looking for UI changes. But I really can't say what I did. I also tested it if I have any feedback to you.

But I don't remember exactly what I did guys :)

**Comment by nuttyartist** [comment] 2018-02-27 15:21
Haha, that's ok. I will close this issue for now. If you ever encounter this issue again feel free to comment and open it.

Thanks for working with us on this one.

**Closed by nuttyartist** 2018-02-27 15:21 UTC
